### PR TITLE
Update baseurl in _config.yml

### PR DESCRIPTION
**Pull request by bas-rustenburg**
Suggested fix for #6 .

### CODE REVIEW

**Comment by bas-rustenburg** [comment]
Needs updating because now it's not linking to css files in posts.

```
[2016-09-06 19:44:06] ERROR `/2016/09/05/ncmc/public/css/hyde.css' not found.
[2016-09-06 19:44:06] ERROR `/2016/09/05/ncmc/public/css/syntax.css' not found.
[2016-09-06 19:44:06] ERROR `/2016/09/05/ncmc/public/css/poole.css' not found.
```

**Comment by bas-rustenburg** [comment]
Should be fixed.

**Comment by jchodera** [comment]
Weird. I thought I needed this to get things to render correctly. I'll give it a try and see what happens.

**Comment by jchodera** [comment]
Rolling back this one too.

**Comment by bas-rustenburg** [comment]
Can we unrevert this? The baseurl was wrong regardless. The sidebar needed to be updated (which I didn't realize was coded up unrobustly, sorry about that!)

**Pull request merged**
