### PR TITLE
Revert "Post truncation"

### PR DESCRIPTION
**Pull request by jchodera**
Reverts choderalab/klogw#17

### CODE REVIEW

**Comment by jchodera** [comment]
Sorry, @bas-rustenburg. Had to revert it because this scheme seems to strip all formatting from the excerpts, making them impossible to comprehend.

I like the idea of having short excerpts on the main page, but not the idea of stripping all formatting to make it happen. Any way to fix that?

**Comment by bas-rustenburg** [comment]
I think that excerpt feature could do the trick. Unfortunately, the truncation isn't safe without stripping html, because it might cut in the middle of a tag.

https://jekyllrb.com/docs/posts/#post-excerpts

Can you check my last commit, and see if that looks better?

**Comment by bas-rustenburg** [comment]
This uses the excerpt feature. It looks like it can automatically detect the first paragraph, and cut it cleanly. Authors can also add an excerpt separator themselves, if they want to cut someplace else in the post.

**Comment by jchodera** [comment]
@bas-rustenburg : This is slightly better, but take a look for yourself:
http://klogw.org

For some posts, it cleanly truncates after one paragraph. For the "How to write a Methods section" post, it basically includes the whole thing.

Any other ideas?

**Comment by bas-rustenburg** [comment]
That is so odd.. there must be something different between the github environment and my local environment. It does truncate the "How to write a methods section" post for me.  Opening a new PR.

**Comment by bas-rustenburg** [comment]
See #19.

**Pull request merged**
