### PR TITLE
Sidebarfix

### PR DESCRIPTION
**Pull request by bas-rustenburg**
I think this should do the trick.

### CODE REVIEW

**Comment by bas-rustenburg** [comment]
@jchodera, @maxentile , this should fix the sidebar. Can you confirm?

**Comment by maxentile** [comment]
Confirmed!

**Comment by jchodera** [comment]
Thanks! But maybe we need to actually fill in some content there?

**Comment by bas-rustenburg** [comment]
How about temporarily copying the blurb from our choderalab.org website until we come up with a custom one about the blog?

> The Chodera lab uses computation and experiment to develop quantitative, multiscale models of the effects of small molecules on biomolecular macromolecules and cellular pathways. To do this, the group utilizes physical models and rigorous statistical mechanics, with overall goals of engineering novel therapeutics and tools for chemical biology, as well as understanding the physical driving forces behind the evolution of resistance mutations. The group makes use of advanced algorithms for molecular dynamics simulations on GPUs and distributed computing platforms, in addition to robot-driven high-throughput experiments focusing on characterizing biophysical interactions between proteins and small molecules.

**Comment by jchodera** [comment]
Sure.

**Pull request merged**
